# Generated by Django 5.1.3 on 2024-11-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='service',
        ),
        migrations.DeleteModel(
            name='Conge',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
