# Generated by Django 5.1.3 on 2024-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appRH', '0002_remove_employe_service_delete_conge_delete_employe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=40)),
                ('date_recrutement', models.DateTimeField(auto_now_add=True)),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('tel', models.CharField(max_length=10)),
                ('situation_fam', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
            ],
        ),
    ]
