# Generated by Django 5.1.3 on 2024-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='name',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
