# Generated by Django 5.1.3 on 2024-12-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0005_candidat_offreemploi_service_conge_contrat_entretien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='offre',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='tel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='conge',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.service'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.candidat'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='employes',
            field=models.ManyToManyField(related_name='faire', to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.service'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.employe'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='offre',
            field=models.ManyToManyField(related_name='inscrire', to='appRH.offreemploi'),
        ),
    ]
