# Generated by Django 5.1.3 on 2024-12-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0007_demandeconge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('Annuel', 'Congé Annuel'), ('Maladie', 'Congé Maladie'), ('Maternité/Paternité', 'Congé Maternité/Paternité'), ('Sans Solde', 'Congé Sans Solde'), ('Autre', 'Autre')], default='Annuel', max_length=50),
        ),
    ]
