# Generated by Django 5.1.3 on 2024-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0008_conge_statut_alter_conge_type_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='jours_utilises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conge',
            name='solde_restant',
            field=models.IntegerField(default=0),
        ),
    ]
