# Generated by Django 5.1.3 on 2024-12-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0010_remove_conge_jours_utilises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='DemandeConge',
        ),
    ]
