# Generated by Django 5.1.3 on 2024-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0013_salaire_avance_massrouf_salaire_retenue_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='demandes_massrouf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaire',
            name='justification_massrouf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
