# Generated by Django 5.1.3 on 2024-12-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0014_salaire_demandes_massrouf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10),
        ),
    ]
