# Generated by Django 5.1.3 on 2024-12-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0015_alter_employe_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='solde_annuel',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='solde_maladie',
        ),
        migrations.AddField(
            model_name='conge',
            name='solde_annuel',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='conge',
            name='solde_maladie',
            field=models.IntegerField(default=10),
        ),
    ]
