# Generated by Django 5.1.3 on 2024-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0018_contrat_archive_contrat_date_archivage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='date_archivage',
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(max_length=50),
        ),
    ]
