# Generated by Django 5.1.3 on 2024-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0019_remove_contrat_archive_remove_contrat_date_archivage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='fichier_contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='renouvellements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', ' STAGE'), ('Autre', 'Autre')], max_length=50),
        ),
    ]
