# Generated by Django 5.1.3 on 2024-12-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0021_remove_contrat_fichier_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='appRH.employe'),
        ),
    ]
