# Generated by Django 5.1.3 on 2025-01-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0022_alter_contrat_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='email',
            new_name='emailC',
        ),
        migrations.RenameField(
            model_name='candidat',
            old_name='nom',
            new_name='nomC',
        ),
        migrations.RenameField(
            model_name='candidat',
            old_name='tel',
            new_name='telC',
        ),
        migrations.AddField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepter', 'Accepté'), ('Refuser', 'Resusé')], default='En attente', max_length=20),
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='offre',
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('En ligne', 'En ligne'), ('Présentiel', 'Présentiel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='offre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appRH.offreemploi'),
        ),
    ]
