# Generated by Django 5.1.3 on 2025-01-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0025_candidat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='offre',
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRH.offreemploi')),
            ],
        ),
    ]
