# Generated by Django 5.1.3 on 2025-01-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0026_remove_candidat_offre_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appRH.offreemploi'),
        ),
    ]
