# Generated by Django 5.1.3 on 2025-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0029_alter_formation_options_formation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='employes',
            field=models.ManyToManyField(related_name='formations', to='appRH.employe'),
        ),
    ]
