# Generated by Django 5.1.3 on 2025-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0030_alter_formation_employes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cv_path',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
