# Generated by Django 5.1.3 on 2025-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0031_alter_candidat_cv_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cv_path',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
