# Generated by Django 5.1.3 on 2025-01-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0032_alter_candidat_cv_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='employes',
            new_name='employe',
        ),
    ]
