# Generated by Django 5.1.3 on 2025-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0035_favori_delete_favoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='formulaire',
            new_name='formateure',
        ),
    ]
