# Generated by Django 5.1.3 on 2025-01-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0036_rename_formulaire_formation_formateure'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='appRH.employe'),
        ),
    ]
