# Generated by Django 5.1.3 on 2025-01-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0037_employe_is_manager_employe_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='manager',
        ),
    ]
