# Generated by Django 5.1.3 on 2025-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0038_remove_employe_is_manager_remove_employe_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formateure',
            field=models.CharField(max_length=100),
        ),
    ]
