# Generated by Django 5.1.3 on 2025-01-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0040_alter_candidat_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appRH.offreemploi'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='formateure',
            field=models.TextField(),
        ),
    ]
