# Generated by Django 5.1.3 on 2025-01-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0041_alter_candidat_offre_alter_formation_formateure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formateure',
            field=models.CharField(max_length=100),
        ),
    ]
