# Generated by Django 5.1.3 on 2025-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0042_alter_formation_formateure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='annee_demande',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaire',
            name='mois_demande',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='decision',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepter', 'Accepté'), ('Refuser', 'Resusé')], default='En attente', max_length=20),
        ),
    ]
