# Generated by Django 5.1.3 on 2025-01-21 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0043_salaire_annee_demande_salaire_mois_demande_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointage_set', to='appRH.employe'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heure_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='statut',
            field=models.CharField(choices=[('Présent', 'Présent'), ('Absent', 'Absent')], default='Présent', max_length=50),
        ),
    ]
