# Generated by Django 5.1.3 on 2025-01-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0046_alter_salaire_avance_massrouf_alter_salaire_prime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('candidat', 'offre')},
        ),
    ]
