# Generated by Django 5.1.3 on 2025-01-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0047_inscription_status_alter_inscription_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='status',
        ),
    ]
