# Generated by Django 5.1.3 on 2025-01-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0048_remove_inscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
