# Generated by Django 5.1.3 on 2025-01-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRH', '0049_inscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='status',
        ),
    ]
